baseURL = 'http://test-pricing-gd.s3-website.eu-central-1.amazonaws.com/pricing/'
languageCode = 'en-us'
title = 'GroupDocs pricing information'
theme = 'mytheme'

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

[params.dynamicmenuid]
  en = "groupdocs-en"
  fr = "groupdocs-fr"
  zh = "groupdocs-zh"
  ru = "groupdocs-ru"
  de = "groupdocs-de"
  ja = "groupdocs-ja"
  es = "groupdocs-es"
  it = "groupdocs-it"
  
  
  

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    languageName = 'Deutsch'
    languageCode = "de"
    title = "Preisinformationen | groupdocs.com"
    weight = 5
    [languages.de.params]
      flag = "flag-de"
    
  [languages.en]
    languageName = 'English'
    languageCode = "en"
    title = "Pricing information | groupdocs.com"
    weight = 3
    [languages.en.params]
      flag = "flag-us"

  [languages.es]
    languageName = 'Español'
    languageCode = "es"
    title = "Información de precio | groupdocs.com"
    weight = 7
    [languages.es.params]
      flag = "flag-es"

  [languages.fr]
    languageName = 'Français'
    languageCode = "fr"
    title = "Information sur les prix | groupdocs.com"
    weight = 2
    [languages.fr.params]
      flag = "flag-fr"

   [languages.it]
    languageName = 'Italiano'
    languageCode = "it"
    title = "Informazioni sui prezzi | groupdocs.com"
    weight = 8
    [languages.it.params]
      flag = "flag-it"

   [languages.ja]
    languageName = '日本語'
    languageCode = "ja"
    title = "価格情報 | groupdocs.com"
    weight = 6
    [languages.ja.params]
     flag = "flag-ja"

   [languages.ru]
    languageName = 'Русский'
    languageCode = "ru"
    title = "Информация о ценах | groupdocs.com"
    weight = 4
    [languages.ru.params]
     flag = "flag-ru"

    [languages.zh]
    languageName = '简体中文'
    languageCode = "zh"
    title = "定价信息 | groupdocs.com"
    weight = 3
    [languages.zh.params]
     flag = "flag-zh"
