baseURL = 'https://example.org/pricing'
languageCode = 'en-us'
title = 'GroupDocs pricing information'
theme = 'mytheme'

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

[params.dynamicmenuid]
  en = "groupdocs-en"
  de = "groupdocs-de"
  es = "groupdocs-es"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    languageName = 'Deutsch'
    languageCode = "de"
    title = "Preisinformationen | groupdocs.com"
    weight = 4
    [languages.de.params]
      flag = "flag-de"
    
  [languages.en]
    languageName = 'English'
    languageCode = "en"
    title = "Pricing information | groupdocs.com"
    weight = 3
    [languages.en.params]
      flag = "flag-us"

  [languages.es]
    languageName = 'Español'
    languageCode = "es"
    title = "Información de precio | groupdocs.com"
    weight = 5
    [languages.es.params]
      flag = "flag-es"