baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Aspose pricing information'
theme = 'mytheme'

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"